name: .NET Core CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x' # Change if you are using a different version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Solution
      run: dotnet build --no-restore --configuration Release

    - name: Run Tests
      run: dotnet test --no-build --verbosity normal

    - name: Publish Build Artifacts
      run: dotnet publish -c Release -o ./output

    - name: Archive Production Build
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-core-build
        path: ./output
